[package]
name = "web-assets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mime = "0.3"

[build-dependencies]
ructe = { version = "0.17", default-features = false, features = ["mime03"] }
